Fix for faction not being disbanded properly when last player leaves Fix for some NoClassDefFoundErrors when Register plugin isn't present and certain economy functions are used